### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Code-acious** [mosajjal/bard-cli#1]
It says command not found and I have done everything as instructed.

**Comment by mosajjal** [comment]
Hi!

Can you please confirm:

- which installation method are you using (binary download or `go install`)
- what is your OS

**Comment by Code-acious** [comment]
go install method

Arch Linux

**Comment by Code-acious** [comment]
go install github.com/mosajjal/bard-cli@latest

After successfull installation
bard-cli --defaultconfig
Says command not found
Anyways i created it manually by 
touch .bardcli.yaml
micro .bardcli.yaml

cookie: entered my session cookie ending with "."
log_level: debug

Ctrl+s (save) and Ctrl+q (exit)

was ready for the revolution ;-)
Butttt... 
Oh Snap :-(
Command not found 🥺🥺.
 Anyways Are U gonna ad support for conversational sessions later??
Currently I use Bard-rs Alfex4936 Built on "RUST"
Do checkout his project too 
But it also has a problem of re-entering session ID (Check the issue section at his page)

**Comment by mosajjal** [comment]
In Arch, by default the GOPATH is not in PATH so you need to provide the full path to run the binary:

`/home/USER/go/bin/bard-cli` 

I might support conversations if there's a good way for me to make it easy in CLI.

**Comment by Code-acious** [comment]
Thanks, I'll check it out.

**Comment by mosajjal** [comment]
feel free to re-open if it's still not working.

**Comment by Code-acious** [comment]
Awesome, thanks!
