### ISSUE TITLE
Escape string symbols (400 Bad Request)

### ISSUE THREAD

**Issue by mamur-rezeki** [mosajjal/bard-cli#12]
https://github.com/mosajjal/bard-cli/blob/b31841d9b5de2afcdf3f1bd97501954f4f727406/bard/bard.go#L104-L108

In my case, it returned error (400) when passing text contains `:`, `'` or `"`.

**Comment by mosajjal** [comment]
yep you're right. will merge your PR to fix this properly :) cheers.
