### ISSUE TITLE
failed to find snim0e value.

### ISSUE THREAD

**Issue by adwaithpj** [mosajjal/bard-cli#16]
![image](https://github.com/mosajjal/bard-cli/assets/77106316/b9858b0e-7745-4e61-b843-955f1503fa71)
Not able to run commands. Tried Clearing the cookies and adding the cookie value again.. works for sometime and this error starts to pop up. 

Won't go until I cleared all the cookies including accounts.google also.

**Comment by mosajjal** [comment]
I've been using this CLI for a while and the cookie shouldn't expire that often. If you're copying the cookie into another machine with a different IP address and especially in a new IP location, that might be the reason why Google is logging you out of your account.

**Comment by adwaithpj** [comment]
I used cloudflare once, after that it got this error.

**Comment by mosajjal** [comment]
this problem still persists? I can't replicate it.

**Comment by adwaithpj** [comment]
> this problem still persists? I can't replicate it. 

No, I changed the browser. Used Edge and took the cookie from there. After that it is okay. 
The problem persisted on chrome. Sometimes it showed traffic overload error and cookie misconfigured error.

Not facing any problem from Edge

**Comment by kingsofteng** [comment]
Got a __Secure-1PSID value from Windows machine. 
Used it in the mac terminal.
Got the same error.
Any workaround?

**Comment by mosajjal** [comment]
Are they the same IP? Also looks like the cookie persists for longer if you're signed in when copying it out. Also keep in mind that browser privacy settings will have an impact on cookie's validity duration

**Comment by kirisakow** [comment]
@mosajjal Hi, I am experiencing the same issue (`FTL failed to ask question: failed to find snim0e value. possibly misconfigured cookies?`) on Android, in a termux terminal. It fails systematically, although I copied the right cookie value from a Firefox Android session on the same device. What do you think? Would you say it is supposed to work or fail?

**Comment by adwaithpj** [comment]
> @mosajjal Hi, I am experiencing the same issue (`FTL failed to ask question: failed to find snim0e value. possibly misconfigured cookies?`) on Android, in a termux terminal. It fails systematically, although I copied the right cookie value from a Firefox Android session on the same device. What do you think? Would you say it is supposed to work or fail?

This error happens when you browser clears your cookies . Use bard in another browser(which doesn't clear the cookies that often) and get the PSID from there.
