### ISSUE TITLE
UTF-8 is not recognized

### ISSUE THREAD

**Issue by pan-szymanowski** [mosajjal/bard-cli#18]
bard-cli does not recognize utf-8 questions. English works perfectly, but not foreign languages. I think, this client should inform the server which encoding user has. Why not to make this option in config file? 
Some details:
My system is Linux
LANG=en_US.UTF-8

**Comment by mosajjal** [comment]
usually, there's UTF8 limitation in the Terminal emulator as well as `neovim`. non-ASCII won't be supported at this stage unfortunately. I'll look into testing it more and see if we can fix it with specific emulators (Kitty/Alacritty)

**Comment by mosajjal** [comment]
made some changes and now UTF-8 works in my Kitty terminal in the latest commit. 
<img width="1132" alt="image" src="https://github.com/mosajjal/bard-cli/assets/10158936/47bc9830-dc48-44a2-84ef-e5acfc966212">

you can install the latest commit using `go install github.com/mosajjal/bard-cli@4219a157a48dedf59b49ac24f06679912b9cc76f` 

let me know if this solves it on your end so I can close this issue

**Comment by pan-szymanowski** [comment]
Hello, could you create a binary for me? 
I have no compiling environment and "go".
Linux amd64.

**Comment by mosajjal** [comment]
please wait for the next release in a few days then :)
