### ISSUE TITLE
Can't figure out proper format for the cookie line in config file

### ISSUE THREAD

**Issue by Mithaxl** [mosajjal/bard-cli#20]
Keep trying all kinds of formats, putting everything on the same line, on different lines, with quotes, without quotes, keeping the words __Secure-1PSID, inputting the cookie Without the words -- nothing works, keep getting those FTL errors, like "FTL failed to ask question..."

Bard itself (via browser) suggests to put the cookie in like this:
cookie:  __Secure-1PSID: 1234567890abcdef1234567890abcdef

But I tried it (with my own cookie, which I got from Chrome Dev Tools as per instructions), and it doesn't work.

Even tried to get a cookie from a Bard session in Firefox ( a different one) still no luck.

What am  I doing wrong? 

What format should that line be in, in the ~/.bardcli.yaml file?

**Comment by mosajjal** [comment]
Made it more clear here: https://github.com/mosajjal/bard-cli/blob/89ece596c049f096a1b351e7f7a5782dd540256f/config.defaults.yaml#L5

let me know if that answers your question

**Comment by Mithaxl** [comment]
Thank you.

I think I've finally solved it.

Cookies obtained from Firefox and ungoogled Chromium weren't working, so I tried installing Chrome (AUR package), and a cookie obtained from Chrome (pasted into config file in the right format, thanks for that again) finally worked, I was able to do a few chats in the terminal.

So,  the problem has been solved, it seems, I was just using wrong cookies.

However, a few minutes later, started running into errors trying to use bard-cli, both in normal and interactive modes.

The error I keep getting is this: "failed to find snim0e value. possibly misconfigured cookies?"

Tried bard-cli in urxvt and in st terminals on manjaro -- same errors.

So, if you can suggest what the issue may be, that'd be great.

Is this supposed to happen occasionally? Is it some issues with google API or something?

Thanks.

**Comment by mosajjal** [comment]
Glad you figured out the cookie format. as for your second comment around your cookies expiring faster than usual, I personally haven't experienced this issue. My setup is Chrome/Firefox on a standard Linux box. I'm also logged into my Google account when I'm copying the cookie value. Also, changing IP addresses between your browser and `bard-cli` could have an affect. I'll close this issue but let me know how it goes :)

**Comment by Mithaxl** [comment]
Thank you again. 
Your last answer (where you mentioned cookies expiring faster than usual) helped me realize I was misinterpreting those errors about "misconfigured cookies". 
For some reason I was only thinking about the cookie not being pasted correctly into bard-cli config file, I wasn't thinking at all about cookies being misconfigured in the actual browser.
So when I realized that the browser settings might have something to do with the issue, I went into Firefox, changed privacy settings for cookies from Custom to Standard, reloaded everything, logged out than logged back in into my Google account, copied the new cookie from the Dev Tools, pasted it into the config file, and voila - now everything works.

Thank you!

**Comment by kirisakow** [comment]
> (...) I wasn't thinking at all about cookies being misconfigured in the actual browser. So when I realized that the browser settings might have something to do with the issue, I went into Firefox, changed privacy settings for cookies from Custom to Standard, reloaded everything, logged out than logged back in into my Google account, copied the new cookie from the Dev Tools, pasted it into the config file, and voila - now everything works.

IMO, a sum-up of this valuable insight should definitely be part of the README file — for people to understand in which cases this CLI tool will work — and in which it won't.
