### ISSUE TITLE
Cookie for captcha?

### ISSUE THREAD

**Issue by ghost** [mosajjal/bard-cli#22]
I get a `2023-08-20T16:26:13-04:00 FTL failed to ask question: status code is not 200: 429` which I think is caused because, if I try to access it on the website, I have to solve a captcha. Is there a cookie for the captcha?

**Comment by mosajjal** [comment]
captcha tokens are short-lived and usually sit on the server side. Currently, `bard-cli` does not offer a solution for this issue.
