### ISSUE TITLE
A zsh shell, installing with brew

### ISSUE THREAD

**Issue by 7Moses** [mosajjal/bard-cli#25]
I tried this,

$ brew install mosajjal/bard-cli/bard-cli

Trying to reach this  'https://github.com/mosajjal/homebrew-bard-cli/'

Is it there, Thanks for any guidance,

**Comment by mosajjal** [comment]
brew formula is not available. you can download the binary from the releases page, and open it from terminal directly. If you get a security warning error, right click on the `bard-cli` file and click open in the menu rather than double click.

**Comment by 7Moses** [comment]
Thanks for the guidance,
