### ISSUE TITLE
[bard-cli Windows] Does not return output, displays error text.

### ISSUE THREAD

**Issue by steb-git** [mosajjal/bard-cli#3]
**Device information**:
> Installation method: ``go install`` thru scoop 
> OS Name:                   Microsoft Windows 11 Home
> OS Version:                10.0.22621 N/A Build 22621
> Config path: ``%userprofile%/.bardcli.yaml``
> bard-cli Binary path: ``%userprofile%/go/bin/bard-cli.exe``
> Is cookie already configured?: yes

---

 **PowerShell Version table output:**
``` pwsh
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
```
---

**Bug sypnosis:**

Does not return bot generated input as expected, returns an error text instead.

**Command Line Output**

Regular without ``--interactive`` flag:
```pwsh
PowerShell 7.3.4
PS C:\Users\steb> bard-cli "Hello, Bard!"
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/mosajjal/bard-cli/bard.(*Bard).Ask(0xc0003cfed8, {0xc0000a2080, 0xc})
        C:/Users/steb/go/pkg/mod/github.com/mosajjal/bard-cli@v0.2.0/bard/bard.go:135 +0x135c
main.main()
        C:/Users/steb/go/pkg/mod/github.com/mosajjal/bard-cli@v0.2.0/main.go:119 +0xf98
PS C:\Users\steb>
```

Using the ``--interactive`` tab
```pwsh
PS C:\Users\steb> bard-cli --interactive

Press Ctrl+D to exit
Q: Hello, Bard!
Q: Hello, Bard!
⣟panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/mosajjal/bard-cli/bard.(*Bard).Ask(0xc0001e9ed8, {0xc000479820, 0xc})
        C:/Users/steb/go/pkg/mod/github.com/mosajjal/bard-cli@v0.2.0/bard/bard.go:135 +0x135c
main.RunInteractive(0xc00013e000?)
        C:/Users/steb/go/pkg/mod/github.com/mosajjal/bard-cli@v0.2.0/interactive.go:27 +0x1f9
main.main()
        C:/Users/steb/go/pkg/mod/github.com/mosajjal/bard-cli@v0.2.0/main.go:114 +0x113c
PS C:\Users\steb>
```

---

**EDIT**: another bug

**Bug sypnosis 2**
Does not find or recognize ``.bard-cli.yaml`` even it is on the correct path instructed and which it exists.

**Command Line Output**

```pwsh
PS C:\Users\steb> bard-cli --config string
2023-05-21T12:04:17+08:00 FTL failed to load config file: open string: The system cannot find the file specified.
PS C:\Users\steb> bard-cli -c string
2023-05-21T12:04:29+08:00 FTL failed to load config file: open string: The system cannot find the file specified.
```

..even though the config file is _actually_ inside the correct directory
```pwsh
PS C:\Users\steb> ls *.yaml

    Directory: C:\Users\steb

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/21/2023 11:21 AM             97 .bardcli.yaml

```

Is there any way or any workaround to get this running again as expected? Thank you!

Best regards,
steb

**Comment by mosajjal** [comment]
Hi, 

first of all, thanks for the good issue :)

I did some minor fixes in the latest commit, could potentially address this issue. you can test by running:

```
go install github.com/mosajjal/bard-cli@main
```

also for your second bug, it looks like you're not providing the full path. try like this:

``` 
bard-cli --config "C:/Users/steb/.bardcli.yaml"
```

**Comment by steb-git** [comment]
Hello!

I really appreciate you taking your time to reply!

Unfortunately, it did not kind of work using the ``bard-cli@main`` branch, however it did return an error text which kind of reflected to your most recent commit: [`commit beb0375`](https://github.com/mosajjal/bard-cli/commit/beb0375ab96bc5e0a80de47b98ea1d577ffc5e26)

**Command Line Output**

Here's the full command log:
```pwsh
PS C:\Users\steb> go install github.com/mosajjal/bard-cli@main
go: downloading github.com/mosajjal/bard-cli v0.2.1-0.20230521050352-beb0375ab96b
PS C:\Users\steb> bard-cli "Hello, bard!"
2023-05-21T14:18:53+08:00 FTL failed to ask question: failed to get answer from bard
PS C:\Users\steb> bard-cli --interactive
Press Ctrl+D to exit
Q: Hello, Bard!
Q: Hello, Bard!
⣾failed to get answer from bard
```

Also, it affected your proposed fix for the second bug with the same error text being returned:
```pwsh
PowerShell 7.3.4
PS C:\Users\steb> bard-cli --config "C:/Users/steb/.bardcli.yaml"
2023-05-21T14:22:05+08:00 FTL failed to ask question: failed to get answer from bard
```

Best regards,
steb

**Comment by mosajjal** [comment]
couldn't replicate this issue in my own machine. try it like this:

```
bard-cli --config "C:/Users/steb/.bardcli.yaml" "what is the meaning of life"
```
