### ISSUE TITLE
feature request: CLI flags for a workaround of the "failed to find snim0e value. possibly misconfigured cookies?" error

### ISSUE THREAD

**Issue by kirisakow** [mosajjal/bard-cli#30]
The `FTL failed to ask question: failed to find snim0e value. possibly misconfigured cookies?` error message reflects quite a nasty issue in Firefox. It makes me update the config file every 2-5 minutes with fresh cookie values; it probably occurs after literally every single submitted prompt. 

~As a result, I'd like bard-cli to have two CLI flags:~

~* one CLI flag to have bard-cli retrieve the latest cookie values for the current prompt, and ignore those currently saved in the config file;~

~* another CLI flag to have bard-cli update the config file with the latest cookie values; the prompt is not mandatory for this one;~

~It should also be possible for the two flags to be combined together, so that bard-cli retrieves the latest cookie values for the current prompt, and also saves them to the config file.~

**Comment by mosajjal** [comment]
Hi, I'm working on an interactive browser launcher to grab the cookies when they expire automatically using Chrome since for whatever reason Chrome cookies remain valid for longer. will publish a draft PR soon. we can tweak the behavior there. Happy to take your input there.

**Comment by kirisakow** [comment]
In the meantime, I led my own little investigation into Firefox, and this is what I got:

### Command to get those cookie values from Firefox user profile

Plain-text values:

```bash
$ sqlite3 ~/.mozilla/firefox/${USER_PROFILE_DIR_NAME}/cookies.sqlite """
SELECT name, value 
FROM moz_cookies 
WHERE host LIKE '%google.com' 
  AND name LIKE '__Secure-1PSID%'
"""
__Secure-1PSID|cooooooookie-vallllllllue-vaaaaaaaaaaaaaalue.
__Secure-1PSIDTS|sidts-cooooooookie-vvvvvvv_aaaaaaa_lueeeee
__Secure-1PSIDCC|ACA-cooooooookie-vaaaaaaaaaaaaaaaa-lueeeee
```

### Command to get those cookie values from Chromium user profile

No plain-text values for those cookies, only the encrypted ones:

```bash
$ sqlite3 ~/snap/chromium/common/chromium/Default/Cookies """
SELECT name, value, encrypted_value 
FROM cookies 
WHERE host_key LIKE '%google.com' 
  AND name LIKE '__Secure-1PSID%'
"""
__Secure-1PSID||v10��...
__Secure-1PSIDTS||v10��...
__Secure-1PSIDCC||v10j��...
```

**Comment by mosajjal** [comment]
yep you can do that. Not keen to put that in the `bard-cli` code though since it breaks too many conventions and security measures. Not to mention Anti-virus vendors will hate it :)

**Comment by kirisakow** [comment]
Then the only bearable solution for bard-cli users is to use Chrome (or Chromium) cookies — something I've already started doing.

Then shouldn't the README be updated accordingly? Something like, "you can use any browser you want, though bear in mind Firefox cookies are renewed very frequently, compared to Chrome"

**Comment by mosajjal** [comment]
yep happy to add a paragraph about it in the README. also curious to understand why this is the case in the first place. seems like a shady operation by Google. MS does the same with Edge interestingly.

**Comment by kirisakow** [comment]
Indeed, I think that Google is taking advantage of the public interest in each of its new products to discreetly favor its own browser, hoping to attract an extra share of users.

So does Microsoft.

**Comment by kirisakow** [comment]
> yep you can do that. Not keen to put that in the `bard-cli` code though since it breaks too many conventions and security measures. Not to mention Anti-virus vendors will hate it :)

You're totally right about that. All things considered, my original proposal was foolish.

Still, the issue remains unaddressed. So, another (better) proposal:

### Pass in the three cookie values as three distinct named CLI arguments

```sh
bard-cli --cookie1psid   "$(whateverCliFuncToGetThatValue1)" \
         --cookie1psidts "$(whateverCliFuncToGetThatValue2)" \
         --cookie1psidcc "$(whateverCliFuncToGetThatValue3)" \
       [ --update-config \ ]
         "prompt text"
```

**Comment by mosajjal** [comment]
#36 should be a step in the right direction. automatically launches a Chrome session, grabs bard cookies and exits. needs to have Bard already logged into by the user since it doesn't allow any interaction atm. feel free to test it.
