### ISSUE TITLE
the `bard-cli -v` problem

### ISSUE THREAD

**Issue by kirisakow** [mosajjal/bard-cli#31]
### Expectation:

https://github.com/mosajjal/bard-cli/blob/3e734be9842a4d65d208d864b8596172c0924eb2/.github/workflows/release.yml#L32

### Reality:

```sh
$ bard-cli -v
bard version UNKNOWN, commit NOT_PROVIDED
```

**Comment by kirisakow** [comment]
Possible fix:

1. Set a `$BARD_CLI_HOME` environment variable.
2. Run:
```sh
$ git -C "$BARD_CLI_HOME" describe --tags
v0.3.6-2-g3e734be
```

**Comment by mosajjal** [comment]
hey mate. I just downloaded the latest version from the releases and it looks fine to me. what's the issue you're facing exactly?

**Comment by kirisakow** [comment]
In fact, whatever the binary —the one installed as a package, or the one compiled from source—, the version string is (was) broken, like I said:

> ### Reality:
> 
>     $ bard-cli -v
>     bard version UNKNOWN, commit NOT_PROVIDED

So I looked into it and fixed it (see #33)

**Comment by mosajjal** [comment]
when you say the one installed as a package, are you referring to these binaries listed here?

https://github.com/mosajjal/bard-cli/releases/tag/v0.3.6

**Comment by kirisakow** [comment]
Certainly. So, again, I have two bard-cli in my OS, plus one on my smartphone:
* one, installed as a package on my desktop computer (Ubuntu 23.04), ie with the command `go install github.com/mosajjal/bard-cli@latest` ;
* another one, installed on my Android phone terminal (termux) like the above ;
* and another one, installed on my desktop computer as code source (and compiled manually), ie with the command `git clone` ;

And both (actually, the three) have the same issue with the version string.

**Comment by mosajjal** [comment]
got it. so the `version` option only works on "official build" of bard-cli through the Github Actions pipeline. none of the above methods actually downloads those binaries. in Linux, you can download this binary:

https://github.com/mosajjal/bard-cli/releases/download/v0.3.6/bard-cli-v0.3.6-linux-amd64.tar.gz

see if this binary has the correct version.

`go install` and `go build` won't build `bard-cli` with the correct parameters.

**Comment by kirisakow** [comment]
Indeed, this one shows the version info correctly:
```
$ ./bard-cli -v
bard version v0.3.6, commit e44d4144363205e1e464b3b03af4d88128eb25ac
```

Also, this binary is ~17MB, while the one I compile from source is 24MB 🤔

**Comment by mosajjal** [comment]
the binary built in the pipeline is a "stripped" one meaning it won't have any debug information in it whereas the default build has them and therefore takes more space. feel free to close this if this answers your question. also closes your PR.
