### ISSUE TITLE
github workflows: left out Go version values

### ISSUE THREAD

**Issue by kirisakow** [mosajjal/bard-cli#32]
### A few left out Go version values:

(shouldn't these be `1.21.3`?)

https://github.com/mosajjal/bard-cli/blob/3e734be9842a4d65d208d864b8596172c0924eb2/.github/workflows/go.yml#L22

https://github.com/mosajjal/bard-cli/blob/3e734be9842a4d65d208d864b8596172c0924eb2/.github/workflows/release.yml#L31

**Comment by mosajjal** [comment]
yeap will be fixed in the next version. shouldn't matter much since 1.20 is still a supported Go release and there's no breaking changes in the dependencies across both versions
