### ISSUE TITLE
feature request: get cookies using browser extension (they keep changing)

### ISSUE THREAD

**Issue by o7adam** [mosajjal/bard-cli#35]
I have had this for like 10min and my cookies changed.  A firefox plugin to grab cookies and place them in the file would be so awesome.  I will help ... if I can.

I love this project so much.  I am just getting started with AI And this is amazing. thank you so much.

**Comment by mosajjal** [comment]
working on an auto cookie grabber from Chrome in #36 :)

**Comment by bpawnzZ** [comment]
I am  having the same issue.  Love the program but only works for about an hr before the cookies are invalid.  is there any solution for this?

**Comment by telgareith** [comment]
Why not use an API key instead? 
See: https://ai.google.dev/pricing
* Free for 60 queries per minute
* Free API key

Other Advantages:
* No cookie Monsters
* Least privileges needed to do the job.
* Businesses can use a Paid plan for their employees.

**Comment by mosajjal** [comment]
I'm open to this as an option. But I feel like this hits the paid tier fairly quickly. I'm working on a server-client architecture so the cookie refresh happens behind the scenes every few seconds.

**Comment by telgareith** [comment]
What are people doing to have more than 1 query per second?

**Comment by mosajjal** [comment]
fair enough. I'll probably switch to API to get rid of all this cookie headache
