### ISSUE TITLE
Clean Output

### ISSUE THREAD

**Issue by BlueBeret** [mosajjal/bard-cli#8]
Currently, the terminal output have some kind of padding that makes it easier to read. However, padding is not good when we need to copy paste it to word editor, because the sentence/paragraph become messed up. Is it possible to generate the clean output (no padding or anything)?

Output from terminal:
![image](https://github.com/mosajjal/bard-cli/assets/63086194/d8b72095-7134-44bf-89ff-55b8f8546b45)

When we copy paste it:
![image](https://github.com/mosajjal/bard-cli/assets/63086194/d3047bb7-8d80-46f0-b998-b4336fe94854)

Clean output (copy directly from browser):
![image](https://github.com/mosajjal/bard-cli/assets/63086194/b40c4ca3-2b7a-4e44-a3a0-7aa7ef58b55a)

nb: notice the line number

**Comment by mosajjal** [comment]
set `NO_COLOR=true` as an environment variable which prevents any styling of the output by `bard-cli`

in Bash/Zsh:
```
NO_COLOR=true bard-cli "what is the meaning of life"
```
